name: 获取和打印 IP 地址

on: 
  # push: #当有代码推送到仓库时触发
  workflow_dispatch: # 手动触发

jobs:
  print-ip:
    runs-on: ubuntu-latest

    steps:
    - name: 打印执行时的 IP 地址
      run: |
        echo "执行时的 IP 地址是："
        output=$(cull ip.sb 2>&1)
        echo "$output"
        if echo "$output" | grep -Fq "404"; then
          exit 1
        fi
