name: 获取和打印 IP 地址

on: 
  push: #当有代码推送到仓库时触发
  workflow_dispatch: # 手动触发

jobs:
  print-ip:
    runs-on: ubuntu-latest

    steps:
    - name: 打印执行时的 IP 地址
      run: |
        echo "1"
        output=$(curl https://ip.sb/ip 2>&1)
        echo "1"
        echo "$output"
        if [ $? -ne 0 ]; then
          echo "命令执行出错，错误信息如上所示。"
          exit 1
        fi
        if echo "$output" | grep -Fq "403"; then
          echo "网页返回 404 - 找不到页面。"
          exit 1
        fi

