name: 获取和打印 IP 地址

on: 
  push: #当有代码推送到仓库时触发
  workflow_dispatch: # 手动触发

jobs:
  print-ip:
    runs-on: ubuntu-latest

    steps:
    - name: 打印执行时的 IP 地址
      run: |
        set -o pipefail
        output=$(cull https://ip.sb/ip) || ret=$?
        echo "$output"

        if echo "$output" | grep -Fq "403"; then
          echo "输出中包含'403'，退出。"
          exit 1
        fi
          
