name: 签到

on:
  schedule:
    - cron: '50 00 * * *' # 上班打卡 (UTC时间 0+8 相当于8:50)
    - cron: '15 03 * * *' # 每日签到检查，如不需要可删除这行
    - cron: '00 10 * * *' # 下班打卡
    - cron: '15 15 * * *' # 每日签到检查，如不需要可删除这行
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 缓存 Python 依赖
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          !~/.cache/pip/log/debug.log
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 执行脚本并检测
      run: |
        set -o pipefail
        output=$(python main.py) || ret=$?
        
        if [ -z "$output" ] && [ -n "$ret" ]; then
        echo "脚本执行失败，但没有输出。退出码为 $ret。"
        exit $ret
        fi

        echo "$output"
        if [ -n "$ret" ]; then
          exit $ret
        elif echo "$output" | grep -Fq "失败"; then
          exit 1
        fi
      env:
        USERS: ${{ secrets.USERS }}
